### ISSUE TITLE
ffmpeg 4.0 support

### ISSUE THREAD

**Issue by kyrios123** [UltraStar-Deluxe/USDX#369]
### ffmpeg is only supported up to 3.3
```
checking version of ffmpeg... configure: error: 

Unsupported ffmpeg version, most recent version supported is 3.3.
```

### Support ffmpeg 4.0
```
checking version of ffmpeg... [4.0]
```
(and then successfully build the application)

### Steps to reproduce

Do a successful build with ffmpeg <= 3.3
Install ffmpeg 4.0 (with devel), execute the same build again.

### Details

Provide some additional information:

- USDX version: 2017.8.0
- Operating System + version: Solus 3 - x86_64 GNU/Linux 4.15.18-67

**Comment by bxabi** [comment]
Hi, I have the same issue on Arch linux. The old ffmpeg is not available anymore.
Can you direct me a bit where in the code should I look around and adapt it to the newer version?

**Comment by bohning** [comment]
@mttronc, maybe you can help here again?

**Comment by mttronc** [comment]
Have not had a look at ffmpeg 4.0 yet. But sure, I can give it a try.
Though I won't be able to test the changes myself, since I use Debian testing which has not migrated to 4.0 yet.

**Comment by mttronc** [comment]
A lot of deprecated stuff got removed in version 4.0.
USDX should upgrade deprecated API calls and test those against currently supported ffmpeg versions before adding ffmpeg 4.0 support.

This is going to require quite a bit of work...

**Comment by bohning** [comment]
Would [acinerella](https://github.com/astoeckel/acinerella) or [libVLC](https://www.videolan.org/vlc/libvlc.html) be a better way to go? @basisbit, what is your take on future FFMPEG support?

**Comment by s09bQ5** [comment]
What if someone wrote a small C application that can be compiled and run at build time to generate pascal headers just for the parts of the FFmpeg API that we need in USDX? This should work at least for the structures and constants. It would be easy to create a list of needed structure elements and constants as USDX will not compile as long as we are still missing some.

Function prototypes rarely change in FFmpeg. We could make the C compiler emit an error if the prototype changed to something unexpected.

**Comment by basisbit** [comment]
Acinerella or libvlc would be awesome instead of directly fiddling with ffmpeg api. If someone has the free time for that, please go ahead! Acinerella actually changed their license to gplv2+ on our request some time ago.
Personally, I lack the time/motivation to code anything in pascal.. Sorry. This is a free/libre oss project, so everyone can participate :)

**Comment by mttronc** [comment]
> This is going to require quite a bit of work...

I take that back.
As far as I can see, USDX is only affected by the removal of audio resampling in libavcodec. The migration is to use `swresample` instead.
Since audio resampling is only used in `UAudioConverter.pas` the changes should be an easy task for somebody who knows what he is doing (not me - I already tried and failed).


I agree with @s09bQ5. The work would be a lot less if you would provide only the ffmpeg functions needed in USDX instead of creating Pascal bindings for the whole API.

**Comment by brianch** [comment]
Should be working now.

The ffmpeg headers (luckily) aren't changing as much as before, the translation itself was only a matter of one night work, the problem is when something big gets deprecated, like happened some time ago, I think in version 2, and force us to change the usdx media code (that I think nobody really understands).

**Comment by bohning** [comment]
Thanks a lot, it is highly appreciated, @brianch.

**Comment by kyrios123** [comment]
thanks a lot for the patch ! :smile:

**Comment by bohning** [comment]
@brianch @basisbit, should the Windows version of [ffmpeg](https://ffmpeg.zeranoe.com/builds/win32/shared/ffmpeg-4.0-win32-shared.zip) be updated to 4.0?

**Comment by basisbit** [comment]
that would drop support for anything older than vista according to [this](https://www.ffmpeg.org/)

> Dropped support for building for Windows XP. The minimum supported Windows version is Windows Vista.

Not sure there is much advantage of ffmpeg 4.0 for usage within a karaoke game. I still see tons of karaoke setups using Windows XP + UltraStar Deluxe out there.
What do you all think about this?

**Comment by brianch** [comment]
I agree, I don't think the update is very important, even more if it drops support for XP.

By the way, I didn't know but according to this the zeranoe builds have dropped support for XP long ago:
https://ffmpeg.zeranoe.com/forum/viewtopic.php?t=2937

In the homepage it also says that "All builds require at least Windows 7 or Mac OS X 10.10"

=====
And about the ffmpeg 4 in general, with it the audio playback is currently being resampled by SDL* (the swresample code isn't working yet). Is this ok (the SDL resampling)? I didn't notice any problems, but if anyone sees something please report it.


*There's also a libsamplerate converter, but I don't remember if we are even checking for the presence of this lib in the configure script, I may take a look into this when I find time.

**Comment by s09bQ5** [comment]
We could do our own build of FFmpeg for Windows. The script for building Zeranoe's toolchain is [here](https://github.com/Zeranoe/mingw-w64-build). The configure options they use for FFmpeg builds are mentioned in the README.txt. Most of the libraries they link to can be dropped. We are only interested in demuxers, decoders, swscale, and swresample.
